// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy0quQCYVVgwZdSTi7Siya1ezuyOC2_Dc',
    appId: '1:286765346546:web:2e0b2c93aac3a936bd6a6b',
    messagingSenderId: '286765346546',
    projectId: 'reading-buddy-2396e',
    authDomain: 'reading-buddy-2396e.firebaseapp.com',
    databaseURL: 'https://reading-buddy-2396e-default-rtdb.firebaseio.com',
    storageBucket: 'reading-buddy-2396e.appspot.com',
    measurementId: 'G-7S6YXXF3VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQISI1uuN0uJAj5fAAh_xi0v40g_kxcAo',
    appId: '1:286765346546:android:6947da96f80c6ffbbd6a6b',
    messagingSenderId: '286765346546',
    projectId: 'reading-buddy-2396e',
    databaseURL: 'https://reading-buddy-2396e-default-rtdb.firebaseio.com',
    storageBucket: 'reading-buddy-2396e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSziV4d0R1M5iUcBvWrjSILKXWf4Zz_a4',
    appId: '1:286765346546:ios:9aefa62f5529f28abd6a6b',
    messagingSenderId: '286765346546',
    projectId: 'reading-buddy-2396e',
    databaseURL: 'https://reading-buddy-2396e-default-rtdb.firebaseio.com',
    storageBucket: 'reading-buddy-2396e.appspot.com',
    iosBundleId: 'com.example.readingBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSziV4d0R1M5iUcBvWrjSILKXWf4Zz_a4',
    appId: '1:286765346546:ios:9aefa62f5529f28abd6a6b',
    messagingSenderId: '286765346546',
    projectId: 'reading-buddy-2396e',
    databaseURL: 'https://reading-buddy-2396e-default-rtdb.firebaseio.com',
    storageBucket: 'reading-buddy-2396e.appspot.com',
    iosBundleId: 'com.example.readingBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy0quQCYVVgwZdSTi7Siya1ezuyOC2_Dc',
    appId: '1:286765346546:web:20f3e6eaae2276acbd6a6b',
    messagingSenderId: '286765346546',
    projectId: 'reading-buddy-2396e',
    authDomain: 'reading-buddy-2396e.firebaseapp.com',
    databaseURL: 'https://reading-buddy-2396e-default-rtdb.firebaseio.com',
    storageBucket: 'reading-buddy-2396e.appspot.com',
    measurementId: 'G-7SVFXE15Y1',
  );
}
